## Aranda Docs Jekyll Theme Settings

## Theme Settings
## ==============

## Jekyll Theme
remote_theme    : "aranda-docs/aranda-jekyll-theme"

## Settings used when generating the website
title           : Aranda Service Desk consola de usuario USDK V8
author          : Aranda Software
version         : 1.0
keywords        : Aranda Software, documentaci칩n, manuales
description     : Hacemos tu gesti칩n de IT mucho m치s f치cil
locale          : "es-CO"
language        : es

## Patterns
# pattern_styles:
#  - /patterns/css/example.css
# pattern_scripts:
#  - /patterns/js/example.js

## Branding files
styles          : /assets/css/style.css
favicon         : /assets/branding/favicon.ico

## Enable to modify the CSS style
#sass:
#  sass_dir: styleguide/_scss
#  style: :compressed

## Output
url             :
baseurl         : /usdkv8
destination     : _site          ## Output folder

## Collection Settings
## ===================

## Outputs the _docs collection !Required
collections:
  pages:
    output: true

## Sets the default attributes for each folder/path
defaults:
  - scope:
      path: ""
    values:
      layout: doc
      sidebar: docs

## General Settings
## ================

# These settings are standard Jekyll Settings, check the Jekyll docs for help

## Preprocessor settings
highlighter: rouge
markdown: kramdown
lsi: false
excerpt_separator: "\n\n"
incremental: false

## Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

## Jekyll Serve
port: 4000


## HTML Compression
## - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

## Files to process
include:
  - .htaccess
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

## Generates Styles
## Disable to prevent styles from being generated.
# sass:
#  sass_dir: _scss
#  style: :compressed
